version: '3'

services:
  nginx:
    image: nginx:latest
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/it-berries.ru:/etc/letsencrypt/live/it-berries.ru
      - ./static/images:/usr/share/nginx/html/images
      - build-volume:/usr/share/nginx/html/build
    command: nginx -g "daemon off";
    links:
      - backend
  certbot:
    image: certbot/certbot
  frontend:
    image: itberriesmsk/explority-frontend:latest
    volumes:
      - build-volume:/app/build
  postgres:
    image: postgres:10
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shut-up-just-push
      POSTGRES_USER: shut-up-just-push
      POSTGES_PASSWORD: shut-up-just-push
    command: postgres -N 1000
  backend:
    image: itberriesmsk/explority-backend:latest
    restart: always
    depends_on: 
      - postgres
    ports:
      - "8080:8080"

volumes:
  build-volume: